version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=wordMaker

    volumes:
      - postgres_14_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    image: word-maker_app:latest
    restart: unless-stopped
    container_name: nodejs-app-container
    depends_on:
      - postgres
      - redis
    ports:
      - "3002:3002"
    volumes:
      - .:/src
    environment:
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DATABASE=wordMaker
      - PG_HOST=postgres-container

volumes:
  postgres_14_data:

